locale: "en-US"
title: Dear M;nd # Title of your site
url: "https://dearming.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""
